### ISSUE TITLE
Suggestion to mention about `ESBUILD_BINARY_PATH` env var in `README.md`.

### ISSUE THREAD

**Issue by grzegorzpokorski** [robert-orlinski/robertorlinski.pl#15]
I think t would be worthy to mention in `README.md` that if someone want to run the project on windows platform (or different) in local environment, should check if have a correct path to executable file (`esbuild.exe` or `esbuild`) in `./helpers/content/mdx.ts`.

Bad path to esbuild executable make impossible to compile and bundle mdx files.

Something like that would be enough: "Take care about correct `ESBUILD_BINARY_PATH` env variable which is defined in `./helpers/content/mdx.ts` file".

For example for me I work on windows 10 x64 and correct path to `esbuild.exe` is: `./node_modules/esbuild-windows-64/esbuild.exe`.

**Comment by robert-orlinski** [comment]
Good point @grzegorzpokorski. I'm not using Windows so I just copied code from `mdx-bundler`'s readme without testing it 😅

I am only wondering, because we have [separate esbuild package for every platform Node recognises](https://github.com/evanw/esbuild/tree/master/npm), shouldn't just installing `esbuild` on Windows work instead of using specific package for windows? 

You can let me know if you can install just `esbuild` and compile MDX using it instead of `esbuild-windows-64`.

**Comment by grzegorzpokorski** [comment]
Hi @robert-orlinski. I only cloned your repo and run npm install. I was little bit confused because in `package.json` is only `esbuild` package defined. Package named `esbuild-windows-64` for my enviroment has been downloaded by `esbuild` package itself.

If I good understand, `esbuild` package downloads additional necessary package depending on OS and in this additional package is located executable file for `esbuild` for specyfic platform. So if i good think there isn't universal path to executable file of `esbuild` for all platforms.

**Comment by robert-orlinski** [comment]
You are right, as I see, also on Mac, there is `eslint` and `esbuild-darwin-64` installed. 

But this is weird that on Mac environment `esbuild` app which is run by `mdx-bundler` is placed in `esbuild` catalogue while on Windows it's placed in `esbuild-windows-64` as you mentioned.

I will get access to Windows environment and test it 🙂 Maybe I will find something interesting!

**Comment by robert-orlinski** [comment]
To be sure - there is no executable in `esbuild` folder in your environment? There is only one in `esbuild-windows-64`, yes?

**Comment by grzegorzpokorski** [comment]
Hi! Below you can see folders related to `esbuild` which appear in `node_modules` folder after run `npm install` command:

![Zrzut ekranu 2022-08-08 234839](https://user-images.githubusercontent.com/27455716/183520868-18b86725-3be2-4852-a358-ba1429badac2.png)

**Comment by grzegorzpokorski** [comment]
After run app by `npm run dev` and navigate to any article (e.g http://localhost:3000/artykuly/nowa-wersja-robertorlinski.pl) ENOENT error apears like on screenshot below:

![Zrzut ekranu 2022-08-08 235511](https://user-images.githubusercontent.com/27455716/183521687-7bcbfcdb-b4c2-46c1-b546-570ccabdb910.png)

**Comment by grzegorzpokorski** [comment]
I just found that following path to executable file of `esbuild` also work correctly on my environment:

```ts
process.env.ESBUILD_BINARY_PATH = path.join(
  process.cwd(),
  'node_modules',
  '.bin',
  'esbuild',
);
```

... and if i good understand [this npm documentation article](https://docs.npmjs.com/cli/v8/configuring-npm/folders#executables), above path could be used as 'universal' for win32 platforms 🤔

**Comment by robert-orlinski** [comment]
@grzegorzpokorski WOW, you are right! What about deleting `ESBUILD_BINARY_PATH` env variable overwritting in general?

Will it work in your environment? If yes, I will check if deployment will work with this deletion. 

I am asking because this `if` related to `ESBUILD_BINARY_PATH` variable, is here because of this [article's part](https://www.alaycock.co.uk/2021/03/mdx-bundler#esbuild-executable) in which Adam is mentioning that Next.js and mdx-bundler don't work together without this `if` and as I remember, this problem was occurring when I was playing with this code for the first time. 

Now it disappeared so I can expect that this is no longer the case - maybe there was some Next.js or mdx-bundler update that solved it 🤔

**Comment by grzegorzpokorski** [comment]
Yeah, you can get rid of whole `if` statement 😂 On my environment - windows 10 x64 - `mdx-bundler` works correctly also without declaring `ESBUILD_BINARY_PATH` variable 🙂

Below more information why `ESBUILD_BINARY_PATH` variable is no longer needed:
 - [`esbuild` update](https://github.com/evanw/esbuild/pull/1621)
 - [reason why `ESBUILD_BINARY_PATH` variable is still longer available](https://github.com/evanw/esbuild/pull/1678)

**Comment by robert-orlinski** [comment]
Hi @grzegorzpokorski! 

I am sorry for this late reply. I haven't noticed any notification regarding your last comment 😮

I removed this `if` then! Thank you for additional links, opening this issue, and the whole conversation 🥳
